version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: kopf
    versions:
    - "> 0.28.3"
  - dependency-name: faker
    versions:
    - 5.8.0
    - 6.0.0
    - 6.1.1
    - 6.4.1
    - 6.5.0
    - 6.5.2
    - 7.0.1
    - 8.1.0
  - dependency-name: pytest-asyncio
    versions:
    - 0.15.0
  - dependency-name: kubernetes-asyncio
    versions:
    - 12.0.1
  - dependency-name: sphinx
    versions:
    - 3.4.0
